[workspace]

members = [
    "flashlender",
    "flashborrower",
    "example/borrower",
    "example/lender",
    "example/minter",
    "tests/eip3156-test-call",
    "tests/minter-test-call",
    "tests/testing"
]